1
mju-likelion/raonair pull request #1
Opened 2021-06-24 02:21 UTC by ypd06021

2021-06-24 13:56 UTC, ndaemy commented on actProjects/App/templates/detailpage.html
> +            height : 60px;
여기서 height가 정해져있어서 글자 세로 정렬이 제멋대로 되는거같아요

2021-06-24 15:13 UTC, Bhanjo commented on actProjects/App/templates/detailpage.html
> +        <div id="center">
이부분에
`
margin: 0 auto;
top: 0%;
width: 1200px;
`
와 같은 css스타일 적용하면 수평 중앙 정렬 가능합니다!

2021-06-25 13:53 UTC, ndaemy reviewed
혹시 raonair라는 최상위에 있는 directory 는 무엇인가요?

2021-06-25 14:00 UTC, ndaemy requested changes
요거 지금은 그냥 html파일로 되어있는데, 장고의 views.py 와 연동 후 장고에서 띄우는 것으로 변경해보시죠!

2021-06-25 14:00 UTC, ndaemy commented on actProjects/App/templates/detailpage.html
> +        .info .link {color: #5085BB;}
요건 tab을 조금 이쁘게 해주시면 가독성이 더 높아질 것 같아요!

2021-06-25 14:00 UTC, ndaemy commented on actProjects/App/templates/detailpage.html
> +                    <h4>실체를 알 수 없는 괴생명체의 공격으로 일상의 모든 것이 사라진 세상, 아이들 대신 죽음을 선택한 아빠의 희생 이후 살아남은 가족들은 위험에 노출된다. 갓 태어난 막내를 포함한 아이들과 함께 소리 없는 사투를 이어가던 엄마 ‘에블린’은 살아남기 위해 새로운 은신처를 찾아 집 밖을 나서지만, 텅 빈 고요함으로 가득
여기 매치가 잘못되어있어요!
지금은 공연시간 - 10000원 / 가격 - 130분 이라고 되어있습니다

2021-06-25 14:00 UTC, ndaemy commented on actProjects/App/templates/detailpage.html
> +                            '                <div class="jibun ellipsis">F2H6+HJ 서울특별시</div>' +
혹시 요기의 F2H6+HJ 는 무슨 뜻일까요..?

2021-06-25 14:00 UTC, ndaemy commented on actProjects/App/templates/detailpage.html
> +                        &starf;  &starf; &starf;  &starf;  &starf;
나중에 별점 4.5 같은 0.5짜리에 대해서는 고민이 조금 필요할 것 같습니다!

2021-06-25 14:26 UTC, ndaemy commented on actProjects/App/templates/detailpage.html
> +                <div class="포스터">
class명에 한글은 추천하지 않습니다..!

2021-06-28 13:47 UTC, ndaemy requested changes

2021-06-28 13:47 UTC, ndaemy commented on actProjects/App/templates/detailpage.html
> +                        <td><span class="circle" img src="{% static 'img/actor1.jpg' %}" > </td>
1. span 태그는 self-closing 태그가 아니라서 여는 태그와 닫는 태그가 있어야 하고, 내용물도 있어야돼요
2. 여기 태그 열고 닫는게 안맞아요

2021-06-28 13:47 UTC, ndaemy commented on actProjects/App/templates/detailpage.html
> +                            </h4>
이런 식으로 작은 글자인 경우에는 div 태그나 p 태그를 쓰는게 일반적이야

2021-06-28 13:50 UTC, ndaemy requested changes
요건 좀 짜치는 것들인데.. 코드 안이뻐지기 좋은 것들이라 깐깐히 본거야

2021-06-28 13:50 UTC, ndaemy commented on actProjects/App/static/css/detailpagestyle.css
> +    background-color : rgb(243, 241, 241);
: (콜론) 왼쪽에는 띄어쓰기 빼고 오른쪽에는 넣고!

2021-06-28 13:50 UTC, ndaemy commented on actProjects/App/static/css/detailpagestyle.css
> +    height :35px;
-_- 이거 안돼요..

2021-06-28 13:50 UTC, ndaemy commented on actProjects/App/static/css/detailpagestyle.css
> +    grid-template-columns: 1fr 1fr ;
마지막 ;(세미콜론) 앞에는 띄어쓰기 넣지 말고!

2021-06-28 13:50 UTC, ndaemy commented on actProjects/App/static/css/detailpagestyle.css
> +.right{
선택자와 여는 중괄호 사이에는 띄어쓰기 한칸!

2021-06-28 13:56 UTC, ndaemy commented on actProjects/App/templates/detailpage.html
>                              &starf;  &starf; &starf;  &starf;  &starf;
띄어쓰기~~ 한칸씩만!!!

2021-06-28 14:16 UTC, ndaemy requested changes

2021-06-28 14:16 UTC, ndaemy commented on actProjects/App/templates/detailpage.html
> +                                <img src="{% static 'img/actor4.jpg' %}"  width=125px; height: 125px;>
요기 보시면 img 태그에 style을 쓰지 않고 그냥 width나 height 속성을 넣을 경우 쌍따옴표 + 숫자 만 쓰도록 되어있어요
요건 잘못된 문법입니다

https://www.w3schools.com/tags/att_img_width.asp

2021-06-28 14:17 UTC, ndaemy commented on actProjects/App/templates/detailpage.html
> +                                <img src="{% static 'img/actor4.jpg' %}"  width=125px; height: 125px;>
+ html 속성에서 키와 값을 구분하는 인자는 :(콜론) 이 아니라 =(이퀄) 입니다

2021-07-01 06:37 UTC, ndaemy commented on actProjects/App/static/css/listpage.css
> +}
불필요한 css는 만들지 않아야 합니다! (필요할 때 만들기!)

2021-07-01 06:38 UTC, ndaemy commented on README.md
> +python actProjects/manage.py runserver
👍

2021-07-01 06:39 UTC, ndaemy requested changes

2021-07-01 06:39 UTC, ndaemy commented on actProjects/actProject/urls.py
> +    path('troupelist/', admin.site.urls),
10번째 줄과 12번째 줄은 저러면 admin 페이지로 가는데, 그걸 원한게 맞어?

2021-07-01 06:40 UTC, ndaemy commented on actProjects/App/templates/detailpage.html
> +            <h3>공연장소</h3> <hr>
지금은 이정도로 괜찮긴 한데, 나중에는 hr 태그보다는 border 를 주는걸 추천드려요
hr 은 html에서 알아서 적당히 디자인을 넣어버리는게 문제될 수 있어서

2021-07-01 06:42 UTC, ndaemy commented on actProjects/App/templates/listpage.html
> +
....?

2021-07-01 06:42 UTC, ypd06021 commented on actProjects/App/static/css/listpage.css
> +}
이거 지워서 푸쉬했었어요 !

2021-07-01 06:42 UTC, ypd06021 commented on actProjects/App/templates/detailpage.html
> +            <h3>공연장소</h3> <hr>
넵 !!

2021-07-01 06:43 UTC, ypd06021 commented on actProjects/App/templates/listpage.html
> +
코드짤때 편하게 보려고 띄워놓은거ㅓ데 이것도 지워서 푸쉬했었어요 !

2021-07-01 06:43 UTC, ndaemy requested changes

2021-07-01 06:43 UTC, ndaemy commented on actProjects/App/static/css/detailpage.css
> +    margin-bottom:s 1.5rem;
이거 틀린 문법일텐데..?

2021-07-01 06:43 UTC, ypd06021 commented on actProjects/App/static/css/detailpage.css
> +    margin-bottom:s 1.5rem;
어떤게 틀리나요 ??

2021-07-01 06:44 UTC, ndaemy commented on actProjects/App/static/css/detailpage.css
> +    margin-bottom:s 1.5rem;
margin bottom 다음에 나오는 s ..?

2021-07-01 06:47 UTC, ypd06021 commented on actProjects/App/static/css/detailpage.css
> +    margin-bottom:s 1.5rem;
ㅎㅎㅎㅎㅎ앗

2021-07-01 06:55 UTC, ndaemy approved these changes

2021-07-01 13:39 UTC, merged