리팩토링: view.py, url.py 재수정
mju-likelion/raonair pull request #13
Opened 2021-07-31 09:52 UTC by ypd06021

2021-08-02 00:57 UTC, Bhanjo commented
한번 테스트 해보려하는데 커밋 다 끝나셨나요?

2021-08-02 01:54 UTC, ndaemy commented
아뇨 아직일거에요 (아마..)

2021-08-04 03:01 UTC, ndaemy commented on actProjects/App/views.py
> +    #         sum += stars_count148+]
음..? 요거 무슨 뜻이죠? ㅋㅋㅋㅋ

2021-08-04 03:02 UTC, ndaemy commented on actProjects/App/views.py
> +                "star_cnt": stars_count,  # 별점수
오 줄이는거 괜찮을거같아요 요거 count를 전부 다 cnt로 바꾸는것도 고민해보시죠

2021-08-04 03:02 UTC, ndaemy requested changes

2021-08-04 03:02 UTC, ndaemy commented on actProjects/App/views.py
> +                "actor": staffss  # 배우 및 극단 프로필
요거, 머지하기 전에 변수 이름은 변경하고 가야할거같아요!

2021-08-04 03:03 UTC, ypd06021 commented on actProjects/App/views.py
> +    #         sum += stars_count148+]
오타에요 .! 새로운 커밋에서 수정했어요 ㅎㅎ

2021-08-04 03:04 UTC, ypd06021 commented on actProjects/App/views.py
> +                "actor": staffss  # 배우 및 극단 프로필
넵 ! staffss 말씀하시는거죠

2021-08-04 03:04 UTC, ypd06021 commented on actProjects/App/views.py
> +                "star_cnt": stars_count,  # 별점수
넵!

2021-08-04 03:05 UTC, ndaemy commented on actProjects/App/views.py
> +                "actor": staffss  # 배우 및 극단 프로필
네넹

2021-08-12 15:41 UTC, ndaemy approved these changes

2021-08-13 19:56 UTC, merged