Feature/search detail api
mju-likelion/raonair pull request #15
Opened 2021-08-04 16:40 UTC by junseokieo

2021-08-05 12:57 UTC, ndaemy requested changes

2021-08-05 12:57 UTC, ndaemy commented on actProjects/App/models.py
> +from django.db import models
models를 두 번 import 할 필요는 없죠!

2021-08-05 12:59 UTC, ndaemy commented on actProjects/App/views.py
> +    play_type = request.GET.get('type', "")
string 처리를 '' (single quote) "" (double quotes) 중에 하나로 통일해주시는게 좋아요!

2021-08-07 06:27 UTC, ndaemy commented on actProjects/App/views.py
> +from django.shortcuts import render, get_object_or_404
얼래 요거 get_object_or_404 import해오시고 사용 안하신건가요?
만약에 사용 안하실거라면 삭제하시는게 좋습니다!

2021-08-07 06:28 UTC, ndaemy commented on actProjects/App/views.py
> +def search_detail(request, type, start):
위의 주석과 함수 선언부가 일치하지 않습니다..!

2021-08-07 06:29 UTC, junseokieo commented on actProjects/App/views.py
> +from django.shortcuts import render, get_object_or_404
어.. 예빈님 이거 수정해서 다시 커밋했는데, 커밋이 새로 안된건가요?

2021-08-07 06:30 UTC, junseokieo commented on actProjects/App/views.py
> +def search_detail(request, type, start):
이것도 마지막 커밋에서 수정했습니다 !

2021-08-07 06:40 UTC, ndaemy commented on actProjects/App/views.py
> +from django.shortcuts import render, get_object_or_404
아 제가 위에서부터 보느라.. ㅋㅋㅋㅋㅋ

2021-08-07 06:41 UTC, ndaemy commented on actProjects/App/views.py
> +def search_detail(request, type, start):
좋습니당~ 요거 대화 resolve 해주시죠 ㅋㅋ

2021-08-07 06:41 UTC, ndaemy commented
@junseokieo 형 이거 다 된건가요?

2021-08-07 06:43 UTC, junseokieo commented
네 그렇습니다

2021-08-07 06:43 UTC, junseokieo commented
> @junseokieo 형 이거 다 된건가요?

네 그렇습니다

2021-08-07 07:08 UTC, ndaemy commented
.DS_Store .gitignore에 넣어주세요~

2021-08-07 07:41 UTC, ndaemy approved these changes

2021-08-07 08:02 UTC, merged