Hanjo
mju-likelion/raonair pull request #2
Opened 2021-06-24 14:38 UTC by Bhanjo

2021-06-25 14:29 UTC, ndaemy requested changes
js 공부 좀 하셨는데요? ㅋㅋㅋㅋ

2021-06-25 14:29 UTC, ndaemy commented on actProjects/App/static/css/style.css
>  	border: 0;
요 파일은 공용으로 사용할 부분과 특정 페이지에 종속되는 부분을 쪼개야 할 것 같습니다!

2021-06-25 14:29 UTC, ndaemy commented on actProjects/App/static/css/style.css
>  input[type="radio"][name="filtering"]:checked + .filterLabel {
css에서 이런 식으로 다양한 선택자를 한 번에 사용하는 것은 가독성을 떨어트리는 주요 요소가 됩니다
좀 더 specific한 class나 id를 사용하시는걸 추천드려요!

2021-06-25 14:29 UTC, ndaemy commented on actProjects/App/static/css/style.css
> +.actInner, .acterInner {
동일한 두 개의 선택자를 , 로 두 번 사용할 필요는 없어보입니다!

2021-06-25 14:29 UTC, ndaemy commented on actProjects/App/static/css/style.css
> +    position: relative;
`position: relative`는 top, right, bottom, left 와 같이 사용하시지 않으면 아무 효과가 없습니다
요거는 불필요한 코드입니다

2021-06-25 14:29 UTC, ndaemy commented on actProjects/App/static/js/searchPage.js
> +    view[i] = document.getElementById('view' + i);
```view.push(document.getElementById('view' + i);```
요런식으로도 가능합니다!

2021-06-25 14:29 UTC, ndaemy commented on actProjects/App/templates/searchPage.html
> +                <div class="contentTitle" style="justify-content: start;"><h2>공연</h2>&nbsp;<a onclick="changeAct()">더보기</a></div>
inline style은 추천하지 않아요. 차라리 contentTitle에 `justify-content:start;` 를 넣는 것을 추천드립니다

2021-06-26 12:32 UTC, Bhanjo commented
`search-play-with-options-style.css`
`header-style.css`
혹시 vw, vh 단위들을 다른 단위로 바꿔주실 수 있나요?
브라우저창 확대 비율에 따라 스타일이 다 망가집니다ㅠ

2021-07-01 04:16 UTC, ndaemy requested changes

2021-07-01 04:16 UTC, ndaemy commented on actProjects/App/static/js/searchPage.js
> +    window.location.href = 'http://127.0.0.1:8000/searchPage';
여기는 `window.location.href = '/searchPage'` 라고 하시던지, `window.location.reload()` 라고 하시는걸 추천드려요.
나중에 서버를 배포한다고 가정했을 때, 그 서버는 127.0.0.1:8000 이 아닐 것이기 때문에, 이렇게 되면 없는 페이지로 가는 상황이 생깁니다.

2021-07-01 04:18 UTC, ndaemy commented on actProjects/App/static/css/theater_detail.css
> +}
위에 것 처럼, 값이 0 일 때는 단위를 제거해주시는 걸 추천드립니다!

2021-07-01 04:18 UTC, ndaemy commented on actProjects/App/static/css/theater_detail.css
> +}
css 적용하실 것이 없다면, 선택자를 굳이 넣지 않아도 돼요!

2021-07-01 04:40 UTC, ndaemy commented on actProjects/App/templates/theater_detail.html
> +                    </div>
와 이거 제발 진짜 DB로 넣어서 이런 개고생 안하기를..

2021-07-01 04:56 UTC, ndaemy commented on actProjects/App/static/css/theater_detail.css
> +    content: '';
음..? 요건 뭐죠?

2021-07-01 04:59 UTC, ndaemy commented on actProjects/App/static/js/searchPage.js
> +        imgEle.src = 'http://127.0.0.1:8000/static/img/actor' + (i + 6) + '.jpg';
요거를 쉽게 해주는 문법 중에 JS [Template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) 이라는 녀석이 있습니다.
여기서는
```javascript
  imgEle.src = `http://127.0.0.1:8000/static/img/actor${i + 6}.jpg`;
```
라고 쓸 수 있어요.

2021-07-01 05:00 UTC, ndaemy commented on actProjects/App/static/css/theater_detail.css
> +    top: 38%;
이런거 % 단위면 나중에 깨질 수도 있습니다! top 같은 속성은 고정 단위 (ex. px) 를 사용하시면 좋아요

2021-07-01 06:16 UTC, Bhanjo commented on actProjects/App/templates/theater_detail.html
> +                    </div>
ㅋㅋㅋㅋㅋㅋㅋ큐ㅠㅠㅠㅠㅠ

2021-07-01 06:23 UTC, merged