feature/search-troupe-detail-api
mju-likelion/raonair pull request #21
Opened 2021-08-06 18:22 UTC by junseokieo

극단 검색결과 더보기 페이지 api

2021-08-07 07:24 UTC, ndaemy commented on actProjects/actProject/urls.py
> +]
마지막에 빈 줄 하나 넣기!!

2021-08-07 15:04 UTC, junseokieo commented
코드리뷰 부탁드립니다 !

2021-08-10 13:31 UTC, ndaemy requested changes

2021-08-10 13:31 UTC, ndaemy commented on actProjects/App/views.py
> +    troupes = filter_query.filter(type__icontains=type)
오호라 👀

2021-08-10 13:31 UTC, ndaemy commented on actProjects/App/views.py
> +    return JsonResponse({'request': 'search_troupe.html'})
끝날 때 빈줄 하나요..!

2021-08-10 13:31 UTC, ndaemy commented on actProjects/App/views.py
> +    troupes = filter_query.filter(type__icontains=type)
(좋다는 얘기입니다)

2021-08-10 13:41 UTC, junseokieo commented on actProjects/App/views.py
> +    troupes = filter_query.filter(type__icontains=type)
from 한조님 입니다 ㅎㅎ

2021-08-10 13:55 UTC, ndaemy approved these changes

2021-08-10 14:22 UTC, merged