헤더, 옵션을 통한 검색 완료
mju-likelion/raonair pull request #4
Opened 2021-06-25 03:49 UTC by skullkim

2021-06-25 16:57 UTC, ndaemy commented on actProjects/App/static/js/search-play-with-options-cli.js
> +}
혹시 파일 이름에 cli는 어떤 뜻인가요?

2021-06-25 17:02 UTC, ndaemy requested changes

2021-06-25 17:02 UTC, ndaemy commented on actProjects/App/static/css/search-play-with-options-style.css
> +    width: 15vw;
이런 식으로 width와 height가 화면 비례인 것은 포스터같이 이미지의 비율이 깨지면 안되는 곳에서는 좋지 않은 방법입니다. 고정 비율로 가주시는게 좋아요.

2021-06-25 17:02 UTC, ndaemy commented on actProjects/App/static/css/search-play-with-options-style.css
> +    justify-content: space-evenly;
justify-content가 여기서 space-evenly이면, 한 row 에 5개 미만의 포스터가 올 경우 왼쪽 정렬이 되지 않고 가운데 정렬이 됩니다.
아직 정하진 않았지만 포스터같은 것들을 정렬할 때는 흔히 왼쪽정렬이므로, 요건 구현 방법을 조금 바꾸셔야 할 것 같아요

2021-06-26 03:45 UTC, skullkim commented on actProjects/App/static/js/search-play-with-options-cli.js
> +}
client라는 의미입니다.  아직 저희 팀의 컨벤션이 정해지지 않아서 제가 벡을 노드로 했을때 쓰던 규칙을 적용했습니다. 제가 노드로 할때는 파일 이름 자체에서 클라이언트용 js임을 알 수 있게 하기 위해 cli를 뒤에 붙입니다.

2021-06-26 03:46 UTC, skullkim commented on actProjects/App/static/css/search-play-with-options-style.css
> +    width: 15vw;
네 수정하겠습니다

2021-06-26 03:46 UTC, skullkim commented on actProjects/App/static/css/search-play-with-options-style.css
> +    justify-content: space-evenly;
네 다른 방식으로 바꾸겠습니다

2021-06-26 05:15 UTC, ndaemy commented
코드리뷰 받으신것들 수정하시고 나면 Resolve conversation 해주시면 보기가 더 편하실거에요!

2021-06-26 12:33 UTC, Bhanjo commented
search-play-with-options-style.css
header-style.css
혹시 vw, vh 단위들을 다른 단위로 바꿔주실 수 있나요?
브라우저창 확대 비율에 따라 스타일이 다 망가집니다ㅠ

2021-06-27 02:35 UTC, ndaemy commented on actProjects/App/views.py
> +    #이미 파일들의 이름을 읽어 온다.
`이미지 파일들` 이라고 쓰신거죠? ㅋㅋㅋㅋ

2021-06-27 02:37 UTC, ndaemy requested changes

2021-06-27 02:37 UTC, ndaemy commented on actProjects/App/static/css/header-style.css
> +    margin-top: 1vh;
한조님도 밑에 써주셨지만, margin 같은 것들은 vh로 쓰면 화면 사이즈 조정에 따라 깨질 위험이 높기 때문에 보통 고정 단위로 사용합니다

2021-06-27 02:41 UTC, ndaemy requested changes

2021-06-27 02:41 UTC, ndaemy commented on actProjects/App/static/css/search-play-with-options-style.css
> +    /* background-color: lightgrey; */
1. padding-bottom과 padding이 중복해서 들어가면 의미가 없습니다.
2. background가 없다면 background-clip의 의미가 없는데, 혹시 추후에 background를 넣을 예정이신건가요?

2021-06-27 04:08 UTC, skullkim commented on actProjects/App/views.py
> +    #이미 파일들의 이름을 읽어 온다.
오타가 있었네요. 다음 커밋때 수정해서 올릴게요.

2021-06-27 04:09 UTC, skullkim commented on actProjects/App/static/css/header-style.css
> +    margin-top: 1vh;
네, 수정하겠습니다.

2021-06-27 04:12 UTC, skullkim commented on actProjects/App/static/css/search-play-with-options-style.css
> +    /* background-color: lightgrey; */
1. 이거는 수정하도록 하겠습니다.
2. background를 넣을 예정은 없습니다. padding에만 색을 넣기 위해 저렇게 한거입니다.

2021-07-01 05:01 UTC, ndaemy approved these changes

2021-07-01 11:42 UTC, merged